const collectionActionTypes = {
    COLLECTION_FETCH_STARTED: 'COLLECTION_FETCH_STARTED',
    COLLECTION_FETCH_SUCCESS: 'COLLECTION_FETCH_SUCCESSFULL',
    COLLECTION_FETCH_FAILED: 'COLLECTION_FETCH_FAILED'
}

export default collectionActionTypes